/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if (n <= 1) {return false;}
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n%i == 0) {return false;}
        }
        return true;

    }
    public long firstPrimeNumberIn(String n) {
        int i = 0;
        while (true) {
            if (isPrime(Long.parseLong(n.substring(i, i+10))) == true) {return Long.parseLong(n.substring(i, i+10));}
            i++;
        }
    }
}
